runtime: python310
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: C:\Users\Xhensil\Downloads\ori\Mental-health-Chatbot-master\static
  static_dir: static

- url: http://127.0.0.1:5000/
  script: auto
